name: Flutter drive iOS
on: push
jobs:
  drive:
    strategy:
      matrix:
        device:
          - "iPhone 8"
          - "iPhone 11 Pro Max"
          - "iPhone 13 Pro Max"
      fail-fast: true
    runs-on: macos-latest
    steps:
      - uses: futureware-tech/simulator-action@v2
        with:
          model: ${{ matrix.device }}
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run Flutter Driver tests
        run: cd example \
          && flutter drive --driver=test_driver/main_app.dart --target=integration-test/basic_example_test.dart \
          && flutter drive --driver=test_driver/main_app.dart --target=integration-test/network_example_test.dart \
          && flutter drive --driver=test_driver/main_app.dart --target=integration-test/namespace_example_test.dart